<MyRoot>:
    
    random_label:random_label
    
    BoxLayout:
        orientation:'vertical'
        Label:
            text:"Press on Generate to \ngenerate a random number"
            font_size:60
            color:0.92,0.45,0.92
        Label:
            id: random_label
            text:"-"
            font_size:60
        Button:
            text:"Generate"
            font_size:34
            size: 100,50
            on_press:root.generate_number()
